"""
Quiz Card Generator — Phase 4.5
================================
V3 Core Goal: Quiz sections display an interactive question card
(A/B/C/D options) as the visual layer while the avatar reads the question.

This is a PROGRAMMATIC generator — no LLM call needed.
The quiz card layout is always the same:
  - Dark background (#0d1117)
  - Question text centred (gold)
  - 4 option buttons (A/B/C/D) in a 2x2 grid
  - Hover highlight + selected state

NOTE: In V3 (Manim edition), quiz cards are rendered by the player's
buildQuizHTML() function using DOM elements. This generator still produces
Three.js .js files for backward compatibility, but the player primarily
uses its built-in HTML quiz card renderer.

No LLM involved — pure Python string template filled from presentation.json data.
"""

import os
import json
import logging
from pathlib import Path
from typing import Dict, Any, List, Optional

logger = logging.getLogger(__name__)

# ─── Three.js Quiz Card Template ─────────────────────────────────────────────
# Self-contained JS: Dark background, question text, 4 option tiles.
# The player calls initScene(container, totalDuration, params).
# When student picks an option, params.onInteract fires with {key, correct}.
_QUIZ_CARD_TEMPLATE = r"""
'use strict';
/* Quiz Card — auto-generated by quiz_card_generator.py
   Section: {section_id}  Question: {question_id}
   DO NOT EDIT — regenerated each pipeline run */

var THREE = window.THREE;

function initScene(container, totalDuration, params) {
    // ── Renderer ──────────────────────────────────────────────────────────
    var renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
    renderer.setPixelRatio(window.devicePixelRatio || 1);
    renderer.setSize(container.clientWidth || 800, container.clientHeight || 450);
    renderer.setClearColor(0x0d1117, 1);
    container.appendChild(renderer.domElement);

    var scene  = new THREE.Scene();
    var aspect = (container.clientWidth || 800) / (container.clientHeight || 450);
    var camera = new THREE.OrthographicCamera(
        -aspect * 5, aspect * 5, 5, -5, 0.1, 100
    );
    camera.position.set(0, 0, 10);
    camera.lookAt(0, 0, 0);

    // ── Colour palette ────────────────────────────────────────────────────
    var CLR = {
        bg:      0x0d1117,
        gold:    0xf5a623,
        teal:    0x4ecdc4,
        surface: 0x161b22,
        border:  0x30363d,
        text:    0xe6edf3,
        correct: 0x3fb950,
        wrong:   0xf85149,
        hover:   0x21262d,
    };

    // ── Helper: canvas text texture ───────────────────────────────────────
    function makeTextTexture(text, opts) {
        opts = opts || {};
        var cw   = opts.width  || 512;
        var ch   = opts.height || 128;
        var fs   = opts.fontSize || 22;
        var col  = opts.color || '#e6edf3';
        var font = opts.font  || 'bold ' + fs + 'px Inter, sans-serif';
        var align = opts.align || 'center';

        var cv = document.createElement('canvas');
        cv.width = cw; cv.height = ch;
        var ctx = cv.getContext('2d');
        ctx.clearRect(0, 0, cw, ch);
        ctx.fillStyle = col;
        ctx.font = font;
        ctx.textAlign = align;
        ctx.textBaseline = 'middle';

        // Word-wrap
        var maxW = cw - 32;
        var words = text.split(' ');
        var lines = [];
        var cur = '';
        for (var i = 0; i < words.length; i++) {
            var test = cur ? cur + ' ' + words[i] : words[i];
            if (ctx.measureText(test).width > maxW && cur) {
                lines.push(cur); cur = words[i];
            } else { cur = test; }
        }
        if (cur) lines.push(cur);

        var lineH = fs * 1.4;
        var startY = ch / 2 - (lines.length - 1) * lineH / 2;
        for (var j = 0; j < lines.length; j++) {
            ctx.fillText(lines[j], align === 'center' ? cw / 2 : 16, startY + j * lineH);
        }

        var tex = new THREE.CanvasTexture(cv);
        tex.needsUpdate = true;
        return tex;
    }

    // ── Helper: rounded rect plane ────────────────────────────────────────
    function makeCard(w, h, color, opacity) {
        var geo = new THREE.PlaneGeometry(w, h);
        var mat = new THREE.MeshBasicMaterial({
            color: color,
            transparent: true,
            opacity: opacity || 1.0,
        });
        return new THREE.Mesh(geo, mat);
    }

    // ── Build question card ───────────────────────────────────────────────
    var Q_TEXT    = {question};
    var OPTS      = {options};
    var CORRECT   = {correct_key};
    var KEYS      = ['A', 'B', 'C', 'D'];

    // Question text
    var qTex  = makeTextTexture(Q_TEXT, {{ width: 768, height: 160, fontSize: 26, color: '#f5a623' }});
    var qPlane = makeCard(aspect * 8, 2.2, CLR.surface, 0.0);
    qPlane.material.map = qTex;
    qPlane.material.transparent = true;
    qPlane.position.set(0, 2.8, 0);
    scene.add(qPlane);

    // Option tiles — 2x2 grid
    var optMeshes = {{}};
    var optLabels  = ['A', 'B', 'C', 'D'];
    var positions = [
        [-aspect * 2.6,  0.6, 0],
        [ aspect * 2.6,  0.6, 0],
        [-aspect * 2.6, -1.2, 0],
        [ aspect * 2.6, -1.2, 0],
    ];

    for (var oi = 0; oi < KEYS.length; oi++) {
        var key  = KEYS[oi];
        var text = key + ': ' + (OPTS[key] || '');
        var pos  = positions[oi];

        var bg = makeCard(aspect * 4.4, 1.4, CLR.surface, 0.0);
        bg.position.set(pos[0], pos[1], 0);
        bg.userData = {{ key: key, baseColor: CLR.surface, hovered: false, answered: false }};
        scene.add(bg);
        optMeshes[key] = bg;

        // Border line (thin plane behind tile)
        var border = makeCard(aspect * 4.44, 1.44, CLR.border, 0.0);
        border.position.set(pos[0], pos[1], -0.01);
        scene.add(border);
        bg.userData.border = border;

        // Label texture
        var lTex = makeTextTexture(text, {{ width: 480, height: 96, fontSize: 20, color: '#e6edf3' }});
        var lPlane = makeCard(aspect * 4.2, 1.2, CLR.surface, 0.0);
        lPlane.material.map = lTex;
        lPlane.position.set(pos[0], pos[1], 0.01);
        scene.add(lPlane);
        bg.userData.label = lPlane;
    }

    // ── Fade-in all elements ──────────────────────────────────────────────
    var allFadeable = [];
    scene.traverse(function(obj) {{
        if (obj.isMesh) allFadeable.push(obj);
    }});

    var fadeT = 0;
    var FADE_DUR = 0.8;

    // ── Interaction state ─────────────────────────────────────────────────
    var answered = false;
    var raycaster = new THREE.Raycaster();
    var mouse     = new THREE.Vector2();
    var optTargets = Object.values(optMeshes);

    function _getHit(nx, ny) {{
        mouse.x = (nx * 2) - 1;
        mouse.y = -(ny * 2) + 1;
        raycaster.setFromCamera(mouse, camera);
        var hits = raycaster.intersectObjects(optTargets);
        return hits.length ? hits[0].object : null;
    }}

    var lastHover = null;

    function onPointerMove(nx, ny, isDrag) {{
        if (answered) return;
        var hit = _getHit(nx, ny);
        if (hit === lastHover) return;
        if (lastHover && !lastHover.userData.answered) {{
            lastHover.material.color.setHex(CLR.surface);
            lastHover.userData.border.material.color.setHex(CLR.border);
        }}
        lastHover = hit;
        if (hit && !hit.userData.answered) {{
            hit.material.color.setHex(CLR.hover);
            hit.userData.border.material.color.setHex(CLR.gold);
        }}
    }}

    function onPointerDown(nx, ny) {{
        if (answered) return;
        var hit = _getHit(nx, ny);
        if (!hit) return;
        var chosen = hit.userData.key;
        var isCorrect = (chosen === CORRECT);
        answered = true;

        // Colour feedback
        for (var k in optMeshes) {{
            var m = optMeshes[k];
            if (k === CORRECT) {{
                m.material.color.setHex(CLR.correct);
                m.userData.border.material.color.setHex(CLR.correct);
            }} else if (k === chosen && !isCorrect) {{
                m.material.color.setHex(CLR.wrong);
                m.userData.border.material.color.setHex(CLR.wrong);
            }}
        }}

        if (params && params.onInteract) {{
            params.onInteract('click', {{ key: chosen, correct: isCorrect }});
        }}
    }}

    function onPointerUp() {{}}

    // ── Animate ───────────────────────────────────────────────────────────
    var animId = null;
    var clock  = new THREE.Clock();

    function animate() {{
        animId = requestAnimationFrame(animate);
        var dt = clock.getDelta();
        fadeT = Math.min(1.0, fadeT + dt / FADE_DUR);

        allFadeable.forEach(function(obj) {{
            if (obj.material) obj.material.opacity = fadeT;
        }});

        renderer.render(scene, camera);
    }}
    animate();

    // ── onResize ──────────────────────────────────────────────────────────
    function onResize(w, h) {{
        renderer.setSize(w, h);
        var a = w / h;
        camera.left   = -a * 5;
        camera.right  =  a * 5;
        camera.updateProjectionMatrix();
    }}

    function onPinchZoom(delta) {{}}  // quiz card does not zoom

    function dispose() {{
        if (animId) cancelAnimationFrame(animId);
        renderer.dispose();
        if (renderer.domElement && renderer.domElement.parentNode) {{
            renderer.domElement.parentNode.removeChild(renderer.domElement);
        }}
    }}

    return {{
        onResize:      onResize,
        onPinchZoom:   onPinchZoom,
        dispose:       dispose,
        onPointerMove: onPointerMove,
        onPointerDown: onPointerDown,
        onPointerUp:   onPointerUp,
    }};
}}
""".strip()


def _js_string(s: str) -> str:
    """Escape a Python string for safe embedding in a JS string literal."""
    return json.dumps(str(s))


def _js_object(d: dict) -> str:
    """Convert a Python dict to a JS object literal string."""
    parts = []
    for k, v in d.items():
        parts.append(f"'{k}': {_js_string(v)}")
    return "{" + ", ".join(parts) + "}"


def generate_quiz_card_js(
    section_id: str,
    question_id: str,
    question_text: str,
    options: Dict[str, str],
    correct_key: str,
) -> str:
    """
    Generate a self-contained Three.js quiz card .js file.

    Args:
        section_id:    Section ID (for comments)
        question_id:   Question ID (q1, q2, ...)
        question_text: The question shown on the card
        options:       Dict {'A': '...', 'B': '...', 'C': '...', 'D': '...'}
        correct_key:   Which key is correct ('A', 'B', 'C', or 'D')

    Returns:
        Complete .js string ready to save
    """
    code = _QUIZ_CARD_TEMPLATE
    code = code.replace("{section_id}", str(section_id))
    code = code.replace("{question_id}", str(question_id))
    code = code.replace("{question}", _js_string(question_text))
    code = code.replace("{options}", _js_object(options))
    code = code.replace("{correct_key}", _js_string(correct_key))
    return code


def run_phase_4_5(
    presentation: Dict[str, Any],
    output_dir: str,
    log_fn=None,
) -> int:
    """
    Phase 4.5: Quiz Card Three.js Generation.

    For every section that has an `understanding_quiz`, generate a
    quiz_card_{section_id}.js file in the threejs/ directory.
    Also handles standalone quiz sections (section_type == 'quiz').

    This is the visual layer displayed while the avatar reads the question.
    The player already handles quiz+threejs sections (line 1069-1070 in player_v3.html).

    Args:
        presentation:  Loaded presentation dict
        output_dir:    Job output directory (parent of threejs/)
        log_fn:        Optional callback log(phase, message)

    Returns:
        Number of quiz card files generated
    """

    def _log(msg):
        logger.info(f"[PHASE 4.5] {msg}")
        if log_fn:
            log_fn("quiz_card_gen", msg)

    _log("Phase 4.5: Generating quiz card Three.js scenes...")

    output_path = Path(output_dir)
    threejs_dir = output_path / "threejs"
    threejs_dir.mkdir(parents=True, exist_ok=True)

    sections = presentation.get("sections", [])
    generated = 0

    for section in sections:
        sec_id = section.get("section_id", "?")
        sec_type = section.get("section_type", "")

        # ── Understanding Quiz (embedded in content/example section) ──────
        uq = section.get("understanding_quiz")
        if uq and uq.get("question"):
            q_text = uq.get("question", "")
            options = uq.get("options", {})
            correct = uq.get("correct", uq.get("correct_option", ""))

            if not options or not correct:
                _log(
                    f"  Sec {sec_id}: understanding_quiz missing options/correct — skipping"
                )
                continue

            js_code = generate_quiz_card_js(
                section_id=str(sec_id),
                question_id="q1",
                question_text=q_text,
                options=options,
                correct_key=correct,
            )

            out_path = threejs_dir / f"quiz_card_{sec_id}.js"
            out_path.write_text(js_code, encoding="utf-8")
            section["quiz_threejs_file"] = f"threejs/quiz_card_{sec_id}.js"
            _log(f"  ✅ Sec {sec_id}: quiz_card_{sec_id}.js generated")
            generated += 1

        # ── Standalone Quiz Section (section_type == 'quiz') ─────────────
        if sec_type == "quiz":
            questions = section.get("questions", [])
            for qi, q in enumerate(questions):
                q_id = q.get("question_id", f"q{qi + 1}")
                q_text = q.get("question_text", q.get("question", ""))
                options = q.get("options", {})
                correct = q.get("correct_option", q.get("correct", ""))

                if not q_text or not options or not correct:
                    _log(f"  Sec {sec_id} {q_id}: incomplete quiz data — skipping")
                    continue

                js_code = generate_quiz_card_js(
                    section_id=str(sec_id),
                    question_id=q_id,
                    question_text=q_text,
                    options=options,
                    correct_key=correct,
                )

                filename = f"quiz_card_{sec_id}_{q_id}.js"
                out_path = threejs_dir / filename
                out_path.write_text(js_code, encoding="utf-8")
                q["quiz_threejs_file"] = f"threejs/{filename}"
                _log(f"  ✅ Sec {sec_id} {q_id}: {filename} generated")
                generated += 1

    _log(f"Phase 4.5 complete: {generated} quiz card file(s) generated.")

    # Explicitly save to presentation.json so the quiz_threejs_file paths propagate back
    pres_path = output_path / "presentation.json"
    try:
        try:
            from core.locks import presentation_lock

            with presentation_lock:
                with open(pres_path, "w", encoding="utf-8") as f:
                    json.dump(presentation, f, indent=2, ensure_ascii=False)
        except ImportError:
            with open(pres_path, "w", encoding="utf-8") as f:
                json.dump(presentation, f, indent=2, ensure_ascii=False)
        _log(f"Saved updated presentation.json with quiz_threejs_file paths.")
    except Exception as e:
        _log(f"Error saving presentation.json in phase 4.5: {e}")

    return generated
