"""
V3 Hard Fail Validator — V3.0

Validates presentation.json generated by V3 Director (Partition Mode).
V3 rules differ from V2.5 in these key areas:

V3 CHANGES vs V2.5:
 - text_layer: ALWAYS "hide" (no text overlays in V3)
 - renderer: "threejs" is now a valid value
 - threejs sections MUST have render_spec with threejs_spec (100+ words)
 - segment_duration_seconds REQUIRED on all content/example sections
 - understanding_quiz REQUIRED on all content/example sections
 - quiz sections: each question must have 3 narration scripts
   (question_script, correct_script, wrong_script) for 3 avatar clips
 - visual_beats: visual_type "threejs" is valid (was only text/diagram/image)
"""

import re
from typing import List, Tuple, Dict, Any

CONTENT_MIN_WORDS = 150
EXAMPLE_MIN_WORDS = 100
THREEJS_SPEC_MIN_WORDS = 30  # Relaxed from 100 — director prompt tuning in progress

REQUIRED_SECTION_TYPES = ["intro", "summary", "recap"]  # memory optional in V3

VAGUE_PHRASES = [
    "appropriate animation", "suitable visual", "relevant content",
    "necessary elements", "various objects", "etc", "and so on",
    "properly animated", "correctly displayed", "accordingly",
    "as needed", "as required", "generic visual", "typical animation",
    "standard display", "some kind of", "some sort of", "a type of",
]

VALID_RENDERERS = {"threejs", "video", "none", "wan", "wan_video"}

VALID_INTERACTION_TYPES = {
    'hover_highlight', 'click_reveal', 'drag_point', 'rotate_inspect', 'slider'
}
INTERACTION_MIN_DURATION = 8.0


class V3ValidatorError(Exception):
    """A single V3 validation failure."""
    def __init__(self, condition: str, section_id, details: str):
        self.condition = condition
        self.section_id = section_id
        self.details = details
        super().__init__(f"[{condition}] Section {section_id}: {details}")


def _count_words(text: str) -> int:
    return len(text.split()) if text else 0


def _check_vague(text: str) -> List[str]:
    lower = text.lower()
    return [p for p in VAGUE_PHRASES if p in lower]


def _get_narration_text(section: dict) -> str:
    n = section.get("narration", "")
    if isinstance(n, dict):
        return n.get("full_text", "")
    return str(n) if n else ""


def _get_segments(section: dict) -> List[dict]:
    n = section.get("narration", {})
    if isinstance(n, dict):
        return n.get("segments", [])
    return []


# ══════════════════════════════════════
# INDIVIDUAL CHECKS
# ══════════════════════════════════════

def _check_text_layer_always_hidden(section: dict) -> List[V3ValidatorError]:
    """V3 Rule: text_layer must ALWAYS be 'hide'. No text overlays."""
    errors = []
    sid = section.get("section_id", 0)
    for i, seg in enumerate(_get_segments(section)):
        dd = seg.get("display_directives", {})
        text_layer = dd.get("text_layer", "")
        if text_layer == "show":
            errors.append(V3ValidatorError(
                "v3_text_layer_show_forbidden",
                sid,
                f"Segment {i}: text_layer='show' is FORBIDDEN in V3. All content is delivered via avatar + Three.js. Set text_layer='hide'."
            ))
    return errors


def _check_renderer_valid(section: dict) -> List[V3ValidatorError]:
    """Renderer must be a known V3 value."""
    errors = []
    sid = section.get("section_id", 0)
    renderer = section.get("renderer", "")
    if renderer and renderer not in VALID_RENDERERS:
        errors.append(V3ValidatorError(
            "v3_invalid_renderer",
            sid,
            f"renderer='{renderer}' is not valid. Must be one of: {VALID_RENDERERS}"
        ))
    if renderer == "manim":
        errors.append(V3ValidatorError(
            "v3_manim_renderer_forbidden",
            sid,
            "renderer='manim' is deprecated in V3. Use renderer='threejs' for Math/Physics sections."
        ))
    return errors


def _check_threejs_spec(section: dict) -> List[V3ValidatorError]:
    """threejs sections MUST have render_spec with threejs_spec (100+ words)."""
    errors = []
    sid = section.get("section_id", 0)
    section_type = section.get("section_type", "")
    renderer = section.get("renderer", "")

    if renderer != "threejs":
        return errors

    render_spec = section.get("render_spec", {})
    if not render_spec:
        errors.append(V3ValidatorError(
            "v3_threejs_missing_render_spec",
            sid,
            "renderer='threejs' but section has no render_spec."
        ))
        return errors

    segment_specs = render_spec.get("segment_specs", [])
    if not segment_specs:
        errors.append(V3ValidatorError(
            "v3_threejs_missing_segment_specs",
            sid,
            "render_spec.segment_specs is empty — no Three.js animation spec provided."
        ))
        return errors

    for i, spec in enumerate(segment_specs):
        threejs_spec = spec.get("threejs_spec", "")
        if not threejs_spec:
            errors.append(V3ValidatorError(
                "v3_threejs_spec_missing",
                sid,
                f"segment_spec[{i}].threejs_spec is missing — required for Three.js generation."
            ))
        elif _count_words(threejs_spec) < THREEJS_SPEC_MIN_WORDS:
            wc = _count_words(threejs_spec)
            errors.append(V3ValidatorError(
                "v3_threejs_spec_too_short",
                sid,
                f"segment_spec[{i}].threejs_spec is {wc} words — minimum is {THREEJS_SPEC_MIN_WORDS} words."
            ))

        spec_duration = spec.get("segment_duration_seconds")
        if not spec_duration:
            errors.append(V3ValidatorError(
                "v3_segment_duration_missing",
                sid,
                f"segment_spec[{i}].segment_duration_seconds not set — Three.js generator needs this."
            ))

        # Check vague language in threejs_spec
        if threejs_spec:
            vague = _check_vague(threejs_spec)
            if vague:
                errors.append(V3ValidatorError(
                    "v3_vague_threejs_spec",
                    sid,
                    f"segment_spec[{i}].threejs_spec contains vague language: {vague}"
                ))

    return errors


def _check_interaction_rules(section: dict) -> List[V3ValidatorError]:
    """GAP 6: interaction field rules on every segment_spec."""
    errors = []
    sid = section.get("section_id", 0)
    render_spec = section.get("render_spec", {})
    if not render_spec:
        return errors

    complexity = section.get("complexity", "simple")

    for i, spec in enumerate(render_spec.get("segment_specs", [])):
        spec_label = f"segment_spec[{i}]"

        # Rule 1 — interaction key must always be present (null or valid object)
        if "interaction" not in spec:
            errors.append(V3ValidatorError(
                "v3_interaction_field_missing",
                sid,
                f"{spec_label}: 'interaction' field is absent — must be null or a valid object"
            ))
            continue

        interaction = spec.get("interaction")
        if interaction is None:
            continue  # null is always valid

        # Rule 2 — type must be one of 5 defined values
        itype = interaction.get("type", "")
        if itype not in VALID_INTERACTION_TYPES:
            errors.append(V3ValidatorError(
                "v3_interaction_invalid_type",
                sid,
                f"{spec_label}: interaction.type '{itype}' is not valid. Must be one of {sorted(VALID_INTERACTION_TYPES)}"
            ))

        # Rule 3 — segment must be long enough for student to discover and act
        duration = spec.get("segment_duration_seconds", 0) or 0
        if float(duration) < INTERACTION_MIN_DURATION:
            errors.append(V3ValidatorError(
                "v3_interaction_duration_too_short",
                sid,
                f"{spec_label}: interaction non-null but segment_duration_seconds={duration} < {INTERACTION_MIN_DURATION}s minimum"
            ))

        # Rule 4 — slider only allowed on complex scenes
        if itype == "slider" and complexity in ("simple", "medium"):
            errors.append(V3ValidatorError(
                "v3_interaction_slider_wrong_complexity",
                sid,
                f"{spec_label}: interaction.type='slider' requires complexity='complex', got '{complexity}'"
            ))

        # Rule 5 — timeout_seconds must be present on interactive beats
        if "timeout_seconds" not in interaction:
            errors.append(V3ValidatorError(
                "v3_interaction_missing_timeout",
                sid,
                f"{spec_label}: interaction object is missing 'timeout_seconds' — player needs this to auto-advance"
            ))

    return errors


def _check_segment_duration(section: dict) -> List[V3ValidatorError]:
    """segment_duration_seconds required at section level for content/example."""
    errors = []
    sid = section.get("section_id", 0)
    section_type = section.get("section_type", "")
    if section_type not in ("content", "example"):
        return errors
    if not section.get("segment_duration_seconds"):
        errors.append(V3ValidatorError(
            "v3_segment_duration_missing",
            sid,
            "content/example sections MUST have segment_duration_seconds set by the Director."
        ))
    return errors


def _check_understanding_quiz(section: dict) -> List[V3ValidatorError]:
    """content/example sections MUST have understanding_quiz (mandatory, no skip condition)."""
    errors = []
    sid = section.get("section_id", 0)
    section_type = section.get("section_type", "")
    if section_type not in ("content", "example"):
        return errors

    quiz = section.get("understanding_quiz", {})
    if not quiz:
        errors.append(V3ValidatorError(
            "v3_understanding_quiz_missing",
            sid,
            "content/example sections MUST include understanding_quiz (no skip condition). "
            "Required fields: question, options (A/B/C/D), correct, explanation, narration."
        ))
        return errors

    if not quiz.get("question"):
        errors.append(V3ValidatorError("v3_understanding_quiz_missing_question", sid, "understanding_quiz.question is empty."))
    opts = quiz.get("options", {})
    if not opts:
        errors.append(V3ValidatorError("v3_understanding_quiz_missing_options", sid, "understanding_quiz.options is empty."))
    elif len(opts) < 4:
        errors.append(V3ValidatorError(
            "v3_understanding_quiz_too_few_options",
            sid,
            f"understanding_quiz must have 4 options (A/B/C/D) — found {len(opts)}: {list(opts.keys())}"
        ))
    if not quiz.get("correct"):
        errors.append(V3ValidatorError("v3_understanding_quiz_missing_answer", sid, "understanding_quiz.correct (answer key) is missing."))
    if not quiz.get("explanation"):
        errors.append(V3ValidatorError("v3_understanding_quiz_missing_explanation", sid, "understanding_quiz.explanation is missing."))

    # C7: narration scripts required for 3-clip avatar generation
    narr = quiz.get("narration", {})
    if not narr:
        errors.append(V3ValidatorError(
            "v3_understanding_quiz_missing_narration",
            sid,
            "understanding_quiz.narration is missing. Required: question_script, correct_script, wrong_script."
        ))
    else:
        for script_key in ("question_script", "correct_script", "wrong_script"):
            if not narr.get(script_key):
                errors.append(V3ValidatorError(
                    "v3_understanding_quiz_missing_narration_script",
                    sid,
                    f"understanding_quiz.narration.{script_key} is missing or empty."
                ))

    return errors


# C7 — image_mode validation rules
VALID_IMAGE_MODES = {"video_reference", "texture", "interactive_hotspot"}


def _check_image_mode_rules(section: dict) -> List[V3ValidatorError]:
    """C7: Enforce image_mode consistency rules on each segment_spec."""
    errors = []
    sid = section.get("section_id", 0)
    render_spec = section.get("render_spec", {})
    if not render_spec:
        return errors

    for i, spec in enumerate(render_spec.get("segment_specs", [])):
        spec_label = f"segment_spec[{i}]"
        image_mode   = spec.get("image_mode")
        image_source = spec.get("image_source")
        renderer     = spec.get("renderer", "")
        interaction  = spec.get("interaction")

        if image_mode is None:
            continue  # no image mode set — no rules apply

        if image_mode not in VALID_IMAGE_MODES:
            errors.append(V3ValidatorError(
                "v3_image_mode_invalid",
                sid,
                f"{spec_label}: image_mode '{image_mode}' is not valid. Must be one of {sorted(VALID_IMAGE_MODES)}"
            ))
            continue

        # Rule 1: image_mode present → image_source must also be present
        if not image_source:
            errors.append(V3ValidatorError(
                "v3_image_mode_missing_source",
                sid,
                f"{spec_label}: image_mode='{image_mode}' is set but image_source is missing — both must be present."
            ))

        # Rule 2: video_reference → renderer must be 'video', no threejs_file
        if image_mode == "video_reference":
            if renderer != "video":
                errors.append(V3ValidatorError(
                    "v3_image_mode_video_ref_wrong_renderer",
                    sid,
                    f"{spec_label}: image_mode='video_reference' requires renderer='video', got '{renderer}'."
                ))
            if spec.get("threejs_file"):
                errors.append(V3ValidatorError(
                    "v3_image_mode_video_ref_has_threejs",
                    sid,
                    f"{spec_label}: image_mode='video_reference' must NOT have a threejs_file (it is a video beat)."
                ))

        # Rule 3: texture/interactive_hotspot → renderer must be 'threejs'
        if image_mode in ("texture", "interactive_hotspot"):
            if renderer != "threejs":
                errors.append(V3ValidatorError(
                    "v3_image_mode_texture_wrong_renderer",
                    sid,
                    f"{spec_label}: image_mode='{image_mode}' requires renderer='threejs', got '{renderer}'."
                ))

        # Rule 4: interactive_hotspot → interaction must be non-null
        if image_mode == "interactive_hotspot" and interaction is None:
            errors.append(V3ValidatorError(
                "v3_image_mode_hotspot_null_interaction",
                sid,
                f"{spec_label}: image_mode='interactive_hotspot' requires a non-null interaction field "
                f"(use hover_highlight or click_reveal)."
            ))

    return errors



def _check_quiz_section(section: dict) -> List[V3ValidatorError]:
    """Quiz sections must have 3 narration scripts per question for 3 avatar clips."""
    errors = []
    sid = section.get("section_id", 0)
    section_type = section.get("section_type", "")
    if section_type != "quiz":
        return errors

    questions = section.get("questions", [])
    if not questions:
        errors.append(V3ValidatorError(
            "v3_quiz_no_questions",
            sid,
            "Quiz section has no questions array."
        ))
        return errors

    for i, q in enumerate(questions):
        narr = q.get("narration", {})
        for script_key in ("question_script", "correct_script", "wrong_script"):
            if not narr.get(script_key):
                errors.append(V3ValidatorError(
                    "v3_quiz_missing_narration_script",
                    sid,
                    f"Question {i} (id={q.get('question_id')}) missing narration.{script_key} — needed for 3 avatar clips."
                ))

        opts = q.get("options", {})
        if len(opts) < 4:
            errors.append(V3ValidatorError(
                "v3_quiz_insufficient_options",
                sid,
                f"Question {i} has {len(opts)} options, minimum is 3 (A/B/C)."
            ))

        if not q.get("correct_option"):
            errors.append(V3ValidatorError(
                "v3_quiz_missing_correct_option",
                sid,
                f"Question {i} has no correct_option set."
            ))

    return errors


def _check_narration_length(section: dict) -> List[V3ValidatorError]:
    """content/example must meet minimum narration word counts."""
    errors = []
    sid = section.get("section_id", 0)
    section_type = section.get("section_type", "")
    if section_type not in ("content", "example"):
        return errors
    text = _get_narration_text(section)
    wc = _count_words(text)
    minimum = CONTENT_MIN_WORDS if section_type == "content" else EXAMPLE_MIN_WORDS
    if wc < minimum:
        errors.append(V3ValidatorError(
            "v3_narration_below_minimum",
            sid,
            f"{section_type} section has {wc} words, minimum is {minimum}."
        ))
    return errors


def _check_display_directives(section: dict) -> List[V3ValidatorError]:
    """display_directives check — non-blocking warning only.
    V3 director early runs may omit these; player handles defaults."""
    return []  # Non-fatal: skipped during director stabilisation phase


# ══════════════════════════════════════
# SECTION VALIDATOR
# ══════════════════════════════════════

def validate_section_v3(section: dict) -> List[V3ValidatorError]:
    """Run all V3 checks on a single section."""
    errors = []
    errors.extend(_check_text_layer_always_hidden(section))
    errors.extend(_check_renderer_valid(section))
    errors.extend(_check_threejs_spec(section))
    errors.extend(_check_interaction_rules(section))
    errors.extend(_check_image_mode_rules(section))   # C7: image mode rules
    errors.extend(_check_segment_duration(section))
    errors.extend(_check_understanding_quiz(section))
    errors.extend(_check_quiz_section(section))
    errors.extend(_check_narration_length(section))
    errors.extend(_check_display_directives(section))
    return errors



# ══════════════════════════════════════
# PRESENTATION VALIDATOR
# ══════════════════════════════════════

def validate_presentation_v3(presentation: dict) -> Tuple[bool, List[V3ValidatorError]]:
    """
    Validate entire V3 presentation.json.

    Returns:
        (is_valid: bool, errors: List[V3ValidatorError])
    """
    all_errors: List[V3ValidatorError] = []
    sections = presentation.get("sections", [])

    # Structure checks
    section_types = {s.get("section_type") for s in sections}
    for required in REQUIRED_SECTION_TYPES:
        if required not in section_types:
            all_errors.append(V3ValidatorError(
                f"v3_missing_{required}_section",
                0,
                f"Presentation is missing required '{required}' section."
            ))

    # Per-section checks
    for section in sections:
        all_errors.extend(validate_section_v3(section))

    return len(all_errors) == 0, all_errors


def format_v3_report(errors: List[V3ValidatorError]) -> str:
    """Format V3 validation errors into a readable report."""
    if not errors:
        return "✅ V3 Validation passed — no issues found."

    lines = [
        "=" * 60,
        "V3 VALIDATOR REPORT",
        "=" * 60,
        f"Total failures: {len(errors)}",
        "",
    ]
    by_condition: Dict[str, List[V3ValidatorError]] = {}
    for e in errors:
        by_condition.setdefault(e.condition, []).append(e)

    for cond, errs in by_condition.items():
        lines.append(f"\n[{cond}] — {len(errs)} occurrence(s)")
        for e in errs:
            lines.append(f"  Section {e.section_id}: {e.details}")

    lines.append("\n" + "=" * 60)
    return "\n".join(lines)


# ══════════════════════════════════════
# CLI USAGE
# ══════════════════════════════════════

if __name__ == "__main__":
    import json, sys
    path = sys.argv[1] if len(sys.argv) > 1 else "presentation.json"
    with open(path) as f:
        data = json.load(f)
    ok, errors = validate_presentation_v3(data)
    print(format_v3_report(errors))
    sys.exit(0 if ok else 1)
