"""
V3 Hard Fail Validator — V3.1

Validates presentation.json generated by V3 Director (Partition Mode).

Fixes from V3.0:
  1.  MANIM_SPEC_MIN_WORDS: 30 → 100  (prompt requires 100+ words per beat)
  2.  REQUIRED_SECTION_TYPES: added "memory" (not optional — always generated)
  3.  VALID_RENDERERS: removed deprecated threejs, wan, wan_video, video
  4.  render_spec.renderer must NOT exist — added check
  5.  understanding_quiz: added explanation_script as 4th required script
  6.  understanding_quiz: added avatar_clips check (all 4 keys required)
  7.  understanding_quiz: added full explanation_visual check
  8.  Added _check_image_to_video_spec() — validates image_to_video_beats word counts
  9.  Added _check_timing_contract() — end_seconds = start + duration
  10. Added _check_text_to_video_spec() — validates video_prompts word counts
  11. Added visual_beats image_source check (visual_type=image must have image_source)
  12. Removed dead _check_display_directives() — _check_text_layer_always_hidden() handles it
  13. understanding_quiz: added option_reveal_seconds (must have exactly 4 values)
"""

import re
from typing import List, Tuple, Dict, Any

CONTENT_MIN_WORDS     = 150
EXAMPLE_MIN_WORDS     = 100
MANIM_SPEC_MIN_WORDS  = 100   # FIX 1: was 30, prompt requires 100+
IMAGE_PROMPT_MIN_WORDS = 100  # image_prompt_start / image_prompt_end
VIDEO_PROMPT_MIN_WORDS = 80   # video_prompt

# FIX 2: memory is NOT optional in V3
REQUIRED_SECTION_TYPES = ["intro", "summary", "memory", "recap"]

VAGUE_PHRASES = [
    "appropriate animation", "suitable visual", "relevant content",
    "necessary elements", "various objects", "etc", "and so on",
    "properly animated", "correctly displayed", "accordingly",
    "as needed", "as required", "generic visual", "typical animation",
    "standard display", "some kind of", "some sort of", "a type of",
]

# FIX 3: removed deprecated/non-V3 renderers (threejs, wan, wan_video, video)
VALID_RENDERERS = {
    "manim",
    "image_to_video",
    "text_to_video",
    "infographic",
    "image",
    "none",
    "per_question",
}

# Valid renderers for explanation_visual
VALID_EV_RENDERERS = {
    "manim", "image_to_video", "text_to_video", "infographic", "image",
}


class V3ValidatorError(Exception):
    """A single V3 validation failure."""

    def __init__(self, condition: str, section_id, details: str):
        self.condition  = condition
        self.section_id = section_id
        self.details    = details
        super().__init__(f"[{condition}] Section {section_id}: {details}")


def _count_words(text: str) -> int:
    return len(text.split()) if text else 0


def _check_vague(text: str) -> List[str]:
    lower = text.lower()
    return [p for p in VAGUE_PHRASES if p in lower]


def _get_narration_text(section: dict) -> str:
    n = section.get("narration", "")
    if isinstance(n, dict):
        return n.get("full_text", "")
    return str(n) if n else ""


def _get_segments(section: dict) -> List[dict]:
    n = section.get("narration", {})
    if isinstance(n, dict):
        return n.get("segments", [])
    return []


# ══════════════════════════════════════════════════════════════
# INDIVIDUAL CHECKS
# ══════════════════════════════════════════════════════════════


def _check_text_layer_always_hidden(section: dict) -> List[V3ValidatorError]:
    """V3 Rule: text_layer must ALWAYS be 'hide'. No text overlays."""
    errors = []
    sid = section.get("section_id", 0)
    for i, seg in enumerate(_get_segments(section)):
        dd         = seg.get("display_directives", {})
        text_layer = dd.get("text_layer", "")
        if text_layer == "show":
            errors.append(V3ValidatorError(
                "v3_text_layer_show_forbidden", sid,
                f"Segment {i}: text_layer='show' is FORBIDDEN in V3. "
                f"All content is delivered via avatar + visual. Set text_layer='hide'.",
            ))
    return errors


def _check_renderer_valid(section: dict) -> List[V3ValidatorError]:
    """Renderer must be a known V3 value."""
    errors = []
    sid      = section.get("section_id", 0)
    renderer = section.get("renderer", "")
    if renderer and renderer not in VALID_RENDERERS:
        errors.append(V3ValidatorError(
            "v3_invalid_renderer", sid,
            f"renderer='{renderer}' is not valid. Must be one of: {sorted(VALID_RENDERERS)}",
        ))
    # FIX 3: explicit error for deprecated renderers that may sneak through
    if renderer in ("threejs", "wan", "wan_video", "video"):
        errors.append(V3ValidatorError(
            "v3_deprecated_renderer", sid,
            f"renderer='{renderer}' is deprecated/invalid in V3. "
            f"Use: manim, image_to_video, text_to_video, none, per_question.",
        ))
    return errors


def _check_manim_spec(section: dict) -> List[V3ValidatorError]:
    """manim sections MUST have render_spec with manim_beats[] array."""
    errors = []
    sid              = section.get("section_id", 0)
    section_renderer = section.get("renderer", "")

    if section_renderer != "manim":
        return errors

    render_spec = section.get("render_spec", {})
    if not render_spec:
        errors.append(V3ValidatorError(
            "v3_manim_missing_render_spec", sid,
            "renderer='manim' but section has no render_spec.",
        ))
        return errors

    # FIX 4: render_spec.renderer must NOT exist in V3
    if "renderer" in render_spec:
        errors.append(V3ValidatorError(
            "v3_render_spec_renderer_forbidden", sid,
            f"render_spec.renderer='{render_spec['renderer']}' must NOT exist in V3. "
            f"The renderer field lives on section, not render_spec.",
        ))

    renderer_reason = render_spec.get("renderer_reason", "").strip()
    if not renderer_reason:
        errors.append(V3ValidatorError(
            "v3_renderer_reason_missing", sid,
            "render_spec.renderer_reason is REQUIRED — explain why manim was chosen.",
        ))

    manim_beats = render_spec.get("manim_beats", [])
    if not manim_beats:
        errors.append(V3ValidatorError(
            "v3_manim_beats_missing", sid,
            "render_spec.manim_beats is missing or empty — required for Manim generation.",
        ))
        return errors

    for i, beat in enumerate(manim_beats):
        spec = beat.get("manim_scene_spec", "")
        if not spec:
            errors.append(V3ValidatorError(
                "v3_manim_spec_missing", sid,
                f"render_spec.manim_beats[{i}].manim_scene_spec is missing.",
            ))
        elif _count_words(spec) < MANIM_SPEC_MIN_WORDS:
            wc = _count_words(spec)
            errors.append(V3ValidatorError(
                "v3_manim_spec_too_short", sid,
                f"render_spec.manim_beats[{i}] is {wc} words — minimum {MANIM_SPEC_MIN_WORDS}. "
                f"Add explicit timing, colours, labels, and object positions.",
            ))
        else:
            vague = _check_vague(spec)
            if vague:
                errors.append(V3ValidatorError(
                    "v3_vague_manim_spec", sid,
                    f"render_spec.manim_beats[{i}] contains vague language: {vague}",
                ))

    if not render_spec.get("total_duration_seconds"):
        errors.append(V3ValidatorError(
            "v3_total_duration_missing", sid,
            "render_spec.total_duration_seconds not set — Manim generator needs this.",
        ))

    return errors


def _check_image_to_video_spec(section: dict) -> List[V3ValidatorError]:
    """FIX 8: image_to_video sections must have valid image_to_video_beats with word counts."""
    errors = []
    sid              = section.get("section_id", 0)
    section_renderer = section.get("renderer", "")

    if section_renderer != "image_to_video":
        return errors

    render_spec = section.get("render_spec", {})
    if not render_spec:
        errors.append(V3ValidatorError(
            "v3_itv_missing_render_spec", sid,
            "renderer='image_to_video' but section has no render_spec.",
        ))
        return errors

    # FIX 4 also applies here
    if "renderer" in render_spec:
        errors.append(V3ValidatorError(
            "v3_render_spec_renderer_forbidden", sid,
            f"render_spec.renderer='{render_spec['renderer']}' must NOT exist in V3.",
        ))

    renderer_reason = render_spec.get("renderer_reason", "").strip()
    if not renderer_reason:
        errors.append(V3ValidatorError(
            "v3_renderer_reason_missing", sid,
            "render_spec.renderer_reason is REQUIRED for image_to_video sections.",
        ))

    beats = render_spec.get("image_to_video_beats", [])
    if not beats:
        errors.append(V3ValidatorError(
            "v3_itv_beats_missing", sid,
            "render_spec.image_to_video_beats is missing or empty.",
        ))
        return errors

    for i, beat in enumerate(beats):
        bid = beat.get("beat_id", i)

        # image_prompt_start — 100+ words
        ips = beat.get("image_prompt_start", "")
        if not ips:
            errors.append(V3ValidatorError(
                "v3_itv_image_prompt_start_missing", sid,
                f"beat[{i}] (id={bid}): image_prompt_start is missing.",
            ))
        elif _count_words(ips) < IMAGE_PROMPT_MIN_WORDS:
            errors.append(V3ValidatorError(
                "v3_itv_image_prompt_start_too_short", sid,
                f"beat[{i}] (id={bid}): image_prompt_start is {_count_words(ips)} words — "
                f"minimum {IMAGE_PROMPT_MIN_WORDS}.",
            ))

        # image_prompt_end — 100+ words
        ipe = beat.get("image_prompt_end", "")
        if not ipe:
            errors.append(V3ValidatorError(
                "v3_itv_image_prompt_end_missing", sid,
                f"beat[{i}] (id={bid}): image_prompt_end is missing.",
            ))
        elif _count_words(ipe) < IMAGE_PROMPT_MIN_WORDS:
            errors.append(V3ValidatorError(
                "v3_itv_image_prompt_end_too_short", sid,
                f"beat[{i}] (id={bid}): image_prompt_end is {_count_words(ipe)} words — "
                f"minimum {IMAGE_PROMPT_MIN_WORDS}.",
            ))

        # video_prompt — 80+ words
        vp = beat.get("video_prompt", "")
        if not vp:
            errors.append(V3ValidatorError(
                "v3_itv_video_prompt_missing", sid,
                f"beat[{i}] (id={bid}): video_prompt is missing.",
            ))
        elif _count_words(vp) < VIDEO_PROMPT_MIN_WORDS:
            errors.append(V3ValidatorError(
                "v3_itv_video_prompt_too_short", sid,
                f"beat[{i}] (id={bid}): video_prompt is {_count_words(vp)} words — "
                f"minimum {VIDEO_PROMPT_MIN_WORDS}.",
            ))

        # duration — max 15s
        dur = beat.get("duration")
        if dur and dur > 15:
            errors.append(V3ValidatorError(
                "v3_itv_beat_duration_exceeds_15s", sid,
                f"beat[{i}] (id={bid}): duration={dur}s exceeds maximum 15s.",
            ))

    if not render_spec.get("total_duration_seconds"):
        errors.append(V3ValidatorError(
            "v3_total_duration_missing", sid,
            "render_spec.total_duration_seconds not set.",
        ))

    return errors


def _check_text_to_video_spec(section: dict) -> List[V3ValidatorError]:
    """FIX 10: text_to_video sections must have video_prompts[] with 80+ words each."""
    errors = []
    sid              = section.get("section_id", 0)
    section_renderer = section.get("renderer", "")

    if section_renderer != "text_to_video":
        return errors

    render_spec = section.get("render_spec", {})
    if not render_spec:
        errors.append(V3ValidatorError(
            "v3_ttv_missing_render_spec", sid,
            "renderer='text_to_video' but section has no render_spec.",
        ))
        return errors

    # FIX 4 also applies
    if "renderer" in render_spec:
        errors.append(V3ValidatorError(
            "v3_render_spec_renderer_forbidden", sid,
            f"render_spec.renderer='{render_spec['renderer']}' must NOT exist in V3.",
        ))

    if not render_spec.get("renderer_reason", "").strip():
        errors.append(V3ValidatorError(
            "v3_renderer_reason_missing", sid,
            "render_spec.renderer_reason is REQUIRED for text_to_video sections.",
        ))

    video_prompts = render_spec.get("video_prompts", [])
    if not video_prompts:
        errors.append(V3ValidatorError(
            "v3_ttv_video_prompts_missing", sid,
            "render_spec.video_prompts is missing or empty for text_to_video section.",
        ))
        return errors

    for i, vpt in enumerate(video_prompts):
        prompt = vpt.get("prompt", "")
        if not prompt:
            errors.append(V3ValidatorError(
                "v3_ttv_video_prompt_missing", sid,
                f"video_prompts[{i}].prompt is missing.",
            ))
        elif _count_words(prompt) < VIDEO_PROMPT_MIN_WORDS:
            errors.append(V3ValidatorError(
                "v3_ttv_video_prompt_too_short", sid,
                f"video_prompts[{i}].prompt is {_count_words(prompt)} words — "
                f"minimum {VIDEO_PROMPT_MIN_WORDS}.",
            ))

    return errors


def _check_timing_contract(section: dict) -> List[V3ValidatorError]:
    """FIX 9: end_seconds must equal start_seconds + duration_seconds exactly."""
    errors = []
    sid          = section.get("section_id", 0)
    section_type = section.get("section_type", "")
    if section_type not in ("content", "example"):
        return errors

    prev_end = None
    for seg in _get_segments(section):
        seg_id = seg.get("segment_id", "?")
        s0     = seg.get("start_seconds")
        e0     = seg.get("end_seconds")
        d0     = seg.get("duration_seconds")

        # Timing contract: end = start + duration
        if all(v is not None for v in [s0, e0, d0]):
            expected_end = round(s0 + d0, 3)
            if abs(expected_end - e0) > 0.15:
                errors.append(V3ValidatorError(
                    "v3_timing_contract_broken", sid,
                    f"Segment {seg_id}: start={s0} + duration={d0} = {expected_end} "
                    f"but end_seconds={e0}. "
                    f"Do NOT round end_seconds independently — derive it from start+duration.",
                ))

        # Contiguous: no gap between previous end and this start
        if prev_end is not None and s0 is not None:
            if abs(s0 - prev_end) > 0.15:
                errors.append(V3ValidatorError(
                    "v3_timing_gap_between_segments", sid,
                    f"Segment {seg_id}: start_seconds={s0} but previous segment "
                    f"ended at {prev_end}. Gap of {round(s0-prev_end,3)}s — segments must be contiguous.",
                ))

        if e0 is not None:
            prev_end = e0

    return errors


def _check_visual_beats(section: dict) -> List[V3ValidatorError]:
    """FIX 11: visual_type=image beats must have image_source set."""
    errors = []
    sid = section.get("section_id", 0)
    for vb in section.get("visual_beats", []):
        if vb.get("visual_type") == "image" and not vb.get("image_source"):
            errors.append(V3ValidatorError(
                "v3_image_beat_missing_image_source", sid,
                f"visual_beat id={vb.get('beat_id','?')} has visual_type='image' "
                f"but image_source is null. Must reference the source filename.",
            ))
    return errors


def _check_segment_duration(section: dict) -> List[V3ValidatorError]:
    """segment_duration_seconds required at section level for content/example."""
    errors = []
    sid          = section.get("section_id", 0)
    section_type = section.get("section_type", "")
    if section_type not in ("content", "example"):
        return errors
    if not section.get("segment_duration_seconds"):
        errors.append(V3ValidatorError(
            "v3_segment_duration_missing", sid,
            "content/example sections MUST have segment_duration_seconds set by the Director.",
        ))
    return errors


def _check_explanation_visual(ev: dict, sid, context: str) -> List[V3ValidatorError]:
    """Shared check for explanation_visual on understanding_quiz and standalone quiz."""
    errors = []

    if not ev:
        errors.append(V3ValidatorError(
            "v3_explanation_visual_missing", sid,
            f"{context}: explanation_visual is REQUIRED.",
        ))
        return errors

    ev_renderer = ev.get("renderer", "")
    if not ev_renderer:
        errors.append(V3ValidatorError(
            "v3_explanation_visual_renderer_missing", sid,
            f"{context}: explanation_visual.renderer is missing.",
        ))
    elif ev_renderer not in VALID_EV_RENDERERS:
        errors.append(V3ValidatorError(
            "v3_explanation_visual_renderer_invalid", sid,
            f"{context}: explanation_visual.renderer='{ev_renderer}' is invalid. "
            f"Must be one of: {sorted(VALID_EV_RENDERERS)}",
        ))

    if not ev.get("renderer_reason", "").strip():
        errors.append(V3ValidatorError(
            "v3_explanation_visual_renderer_reason_missing", sid,
            f"{context}: explanation_visual.renderer_reason is REQUIRED.",
        ))

    if not ev.get("display_text", "").strip():
        errors.append(V3ValidatorError(
            "v3_explanation_visual_display_text_missing", sid,
            f"{context}: explanation_visual.display_text is REQUIRED.",
        ))

    if not ev.get("duration_seconds"):
        errors.append(V3ValidatorError(
            "v3_explanation_visual_duration_missing", sid,
            f"{context}: explanation_visual.duration_seconds is REQUIRED.",
        ))

    # Renderer-specific spec checks
    if ev_renderer == "manim":
        ev_mb = ev.get("manim_beats", [])
        if not ev_mb:
            # fallback: old-style manim_scene_spec string
            mss = ev.get("manim_scene_spec", "")
            if not mss:
                errors.append(V3ValidatorError(
                    "v3_explanation_visual_manim_spec_missing", sid,
                    f"{context}: explanation_visual.renderer=manim but "
                    f"manim_beats[] is missing.",
                ))
            elif _count_words(mss) < MANIM_SPEC_MIN_WORDS:
                errors.append(V3ValidatorError(
                    "v3_explanation_visual_manim_spec_too_short", sid,
                    f"{context}: explanation_visual.manim_scene_spec is "
                    f"{_count_words(mss)} words — minimum {MANIM_SPEC_MIN_WORDS}.",
                ))
        else:
            for i, b in enumerate(ev_mb):
                wc = _count_words(b.get("manim_scene_spec", ""))
                if wc < MANIM_SPEC_MIN_WORDS:
                    errors.append(V3ValidatorError(
                        "v3_explanation_visual_manim_beat_too_short", sid,
                        f"{context}: explanation_visual.manim_beats[{i}] is "
                        f"{wc} words — minimum {MANIM_SPEC_MIN_WORDS}.",
                    ))

    elif ev_renderer == "image_to_video":
        ev_itv = ev.get("image_to_video_beats", [])
        if not ev_itv:
            errors.append(V3ValidatorError(
                "v3_explanation_visual_itv_beats_missing", sid,
                f"{context}: explanation_visual.renderer=image_to_video but "
                f"image_to_video_beats[] is missing.",
            ))
        else:
            for i, b in enumerate(ev_itv):
                for field, minw in [("image_prompt_start", IMAGE_PROMPT_MIN_WORDS),
                                    ("image_prompt_end",   IMAGE_PROMPT_MIN_WORDS),
                                    ("video_prompt",       VIDEO_PROMPT_MIN_WORDS)]:
                    wc = _count_words(b.get(field, ""))
                    if wc < minw:
                        errors.append(V3ValidatorError(
                            "v3_explanation_visual_itv_prompt_too_short", sid,
                            f"{context}: explanation_visual.image_to_video_beats[{i}]."
                            f"{field} is {wc} words — minimum {minw}.",
                        ))

    elif ev_renderer == "text_to_video":
        vp = ev.get("video_prompt", "")
        if not vp:
            errors.append(V3ValidatorError(
                "v3_explanation_visual_video_prompt_missing", sid,
                f"{context}: explanation_visual.renderer=text_to_video but "
                f"video_prompt is missing.",
            ))
        elif _count_words(vp) < VIDEO_PROMPT_MIN_WORDS:
            errors.append(V3ValidatorError(
                "v3_explanation_visual_video_prompt_too_short", sid,
                f"{context}: explanation_visual.video_prompt is "
                f"{_count_words(vp)} words — minimum {VIDEO_PROMPT_MIN_WORDS}.",
            ))

    return errors


def _check_understanding_quiz(section: dict) -> List[V3ValidatorError]:
    """content/example sections MUST have a complete understanding_quiz."""
    errors = []
    sid          = section.get("section_id", 0)
    section_type = section.get("section_type", "")
    if section_type not in ("content", "example"):
        return errors

    quiz = section.get("understanding_quiz", {})
    if not quiz:
        errors.append(V3ValidatorError(
            "v3_understanding_quiz_missing", sid,
            "content/example sections MUST include understanding_quiz. No skip condition.",
        ))
        return errors

    if not quiz.get("question"):
        errors.append(V3ValidatorError(
            "v3_understanding_quiz_missing_question", sid,
            "understanding_quiz.question is empty.",
        ))

    opts = quiz.get("options", {})
    if not opts:
        errors.append(V3ValidatorError(
            "v3_understanding_quiz_missing_options", sid,
            "understanding_quiz.options is empty.",
        ))
    elif len(opts) < 4:
        errors.append(V3ValidatorError(
            "v3_understanding_quiz_too_few_options", sid,
            f"understanding_quiz must have 4 options (A/B/C/D) — found {len(opts)}: {list(opts.keys())}",
        ))

    if not quiz.get("correct"):
        errors.append(V3ValidatorError(
            "v3_understanding_quiz_missing_answer", sid,
            "understanding_quiz.correct (answer key) is missing.",
        ))

    if not quiz.get("explanation"):
        errors.append(V3ValidatorError(
            "v3_understanding_quiz_missing_explanation", sid,
            "understanding_quiz.explanation is missing.",
        ))

    # Narration scripts — FIX 5: now checks all 4 scripts
    narr = quiz.get("narration", {})
    if not narr:
        errors.append(V3ValidatorError(
            "v3_understanding_quiz_missing_narration", sid,
            "understanding_quiz.narration is missing. "
            "Required: question_script, correct_script, wrong_script, explanation_script.",
        ))
    else:
        for script_key in ("question_script", "correct_script",
                           "wrong_script", "explanation_script"):   # FIX 5
            if not narr.get(script_key):
                errors.append(V3ValidatorError(
                    "v3_understanding_quiz_missing_narration_script", sid,
                    f"understanding_quiz.narration.{script_key} is missing or empty.",
                ))

        # FIX 13: option_reveal_seconds must have exactly 4 values
        ors = narr.get("option_reveal_seconds", [])
        if not ors:
            errors.append(V3ValidatorError(
                "v3_understanding_quiz_missing_option_reveal_seconds", sid,
                "understanding_quiz.narration.option_reveal_seconds is missing. "
                "Must have exactly 4 float values (one per A/B/C/D button).",
            ))
        elif len(ors) != 4:
            errors.append(V3ValidatorError(
                "v3_understanding_quiz_option_reveal_seconds_wrong_count", sid,
                f"understanding_quiz.narration.option_reveal_seconds has {len(ors)} values — "
                f"must have exactly 4 (one per A/B/C/D button).",
            ))

    # FIX 6: avatar_clips — all 4 keys required
    clips = quiz.get("avatar_clips", {})
    if not clips:
        errors.append(V3ValidatorError(
            "v3_understanding_quiz_avatar_clips_missing", sid,
            "understanding_quiz.avatar_clips is missing. "
            "Required keys: question, correct, wrong, explanation.",
        ))
    else:
        for clip_key in ("question", "correct", "wrong", "explanation"):
            if not clips.get(clip_key):
                errors.append(V3ValidatorError(
                    "v3_understanding_quiz_avatar_clip_missing", sid,
                    f"understanding_quiz.avatar_clips.{clip_key} is missing. "
                    f"All 4 clips are required for the player interaction flow.",
                ))

    # FIX 7: explanation_visual — full check
    ev = quiz.get("explanation_visual", {})
    errors.extend(_check_explanation_visual(ev, sid, "understanding_quiz"))

    return errors


def _check_quiz_section(section: dict) -> List[V3ValidatorError]:
    """Standalone quiz sections: each question needs 4 scripts, 4 clips, explanation_visual."""
    errors = []
    sid              = section.get("section_id", 0)
    section_type     = section.get("section_type", "")
    section_renderer = section.get("renderer", "")

    if section_type != "quiz" and section_renderer != "per_question":
        return errors

    questions = section.get("questions", [])
    if not questions:
        errors.append(V3ValidatorError(
            "v3_quiz_no_questions", sid, "Quiz section has no questions array.",
        ))
        return errors

    for i, q in enumerate(questions):
        qid  = q.get("question_id", i)
        narr = q.get("narration", {})

        # 4 scripts
        for script_key in ("question_script", "correct_script",
                           "wrong_script", "explanation_script"):
            if not narr.get(script_key):
                errors.append(V3ValidatorError(
                    "v3_quiz_missing_narration_script", sid,
                    f"Question {i} (id={qid}) missing narration.{script_key}.",
                ))

        # options
        opts = q.get("options", {})
        if len(opts) < 4:
            errors.append(V3ValidatorError(
                "v3_quiz_insufficient_options", sid,
                f"Question {i} has {len(opts)} options — minimum 4 (A/B/C/D).",
            ))

        if not q.get("correct_option"):
            errors.append(V3ValidatorError(
                "v3_quiz_missing_correct_option", sid,
                f"Question {i} (id={qid}) has no correct_option.",
            ))

        # explanation_visual — full check
        ev = q.get("explanation_visual", {})
        errors.extend(_check_explanation_visual(ev, sid, f"Quiz question {i} (id={qid})"))

    return errors


def _check_narration_length(section: dict) -> List[V3ValidatorError]:
    """content/example must meet minimum narration word counts."""
    errors = []
    sid          = section.get("section_id", 0)
    section_type = section.get("section_type", "")
    if section_type not in ("content", "example"):
        return errors
    text    = _get_narration_text(section)
    wc      = _count_words(text)
    minimum = CONTENT_MIN_WORDS if section_type == "content" else EXAMPLE_MIN_WORDS
    if wc < minimum:
        errors.append(V3ValidatorError(
            "v3_narration_below_minimum", sid,
            f"{section_type} section has {wc} words — minimum is {minimum}.",
        ))
    return errors


# ══════════════════════════════════════════════════════════════
# SECTION VALIDATOR
# ══════════════════════════════════════════════════════════════


def validate_section_v3(section: dict) -> List[V3ValidatorError]:
    """Run all V3 checks on a single section."""
    errors = []
    errors.extend(_check_text_layer_always_hidden(section))
    errors.extend(_check_renderer_valid(section))
    errors.extend(_check_manim_spec(section))
    errors.extend(_check_image_to_video_spec(section))   # FIX 8
    errors.extend(_check_text_to_video_spec(section))    # FIX 10
    errors.extend(_check_timing_contract(section))       # FIX 9
    errors.extend(_check_visual_beats(section))          # FIX 11
    errors.extend(_check_segment_duration(section))
    errors.extend(_check_understanding_quiz(section))
    errors.extend(_check_quiz_section(section))
    errors.extend(_check_narration_length(section))
    # FIX 12: _check_display_directives removed — was dead code returning []
    return errors


# ══════════════════════════════════════════════════════════════
# PRESENTATION VALIDATOR
# ══════════════════════════════════════════════════════════════


def validate_presentation_v3(presentation: dict) -> Tuple[bool, List[V3ValidatorError]]:
    """
    Validate entire V3 presentation.json.

    Returns:
        (is_valid: bool, errors: List[V3ValidatorError])
    """
    all_errors: List[V3ValidatorError] = []
    sections = presentation.get("sections", [])

    # Required section types — FIX 2: memory is required
    section_types = {s.get("section_type") for s in sections}
    for required in REQUIRED_SECTION_TYPES:
        if required not in section_types:
            all_errors.append(V3ValidatorError(
                f"v3_missing_{required}_section", 0,
                f"Presentation is missing required '{required}' section.",
            ))

    # Per-section checks
    for section in sections:
        all_errors.extend(validate_section_v3(section))

    return len(all_errors) == 0, all_errors


def format_v3_report(errors: List[V3ValidatorError]) -> str:
    """Format V3 validation errors into a readable report."""
    if not errors:
        return "✅ V3 Validation passed — no issues found."

    lines = [
        "=" * 60,
        "V3 VALIDATOR REPORT",
        "=" * 60,
        f"Total failures: {len(errors)}",
        "",
    ]
    by_condition: Dict[str, List[V3ValidatorError]] = {}
    for e in errors:
        by_condition.setdefault(e.condition, []).append(e)

    for cond, errs in by_condition.items():
        lines.append(f"\n[{cond}] — {len(errs)} occurrence(s)")
        for e in errs:
            lines.append(f"  Section {e.section_id}: {e.details}")

    lines.append("\n" + "=" * 60)
    return "\n".join(lines)


# ══════════════════════════════════════════════════════════════
# CLI USAGE
# ══════════════════════════════════════════════════════════════

if __name__ == "__main__":
    import json, sys

    path = sys.argv[1] if len(sys.argv) > 1 else "presentation.json"
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    ok, errors = validate_presentation_v3(data)
    print(format_v3_report(errors))
    sys.exit(0 if ok else 1)