"""
V3 Hard Fail Validator — V3.0 (Manim Edition)

Validates presentation.json generated by V3 Director (Partition Mode).
V3 rules:

V3 CHANGES (Manim replaces Three.js):
 - text_layer: ALWAYS "hide" (no text overlays in V3)
 - renderer: "manim" is now the primary visual renderer
 - manim sections MUST have render_spec with manim_scene_spec (30+ words)
 - segment_duration_seconds REQUIRED on all content/example sections
 - understanding_quiz REQUIRED on all content/example sections
 - quiz sections: each question must have 3 narration scripts
   (question_script, correct_script, wrong_script) for 3 avatar clips
 - visual_beats: visual_type "manim" is valid
"""

import re
from typing import List, Tuple, Dict, Any

CONTENT_MIN_WORDS = 150
EXAMPLE_MIN_WORDS = 100
MANIM_SPEC_MIN_WORDS = 30  # Relaxed from 100 — director prompt tuning in progress

REQUIRED_SECTION_TYPES = ["intro", "summary", "recap"]  # memory optional in V3

VAGUE_PHRASES = [
    "appropriate animation",
    "suitable visual",
    "relevant content",
    "necessary elements",
    "various objects",
    "etc",
    "and so on",
    "properly animated",
    "correctly displayed",
    "accordingly",
    "as needed",
    "as required",
    "generic visual",
    "typical animation",
    "standard display",
    "some kind of",
    "some sort of",
    "a type of",
]

VALID_RENDERERS = {"manim", "video", "none", "wan", "wan_video"}


class V3ValidatorError(Exception):
    """A single V3 validation failure."""

    def __init__(self, condition: str, section_id, details: str):
        self.condition = condition
        self.section_id = section_id
        self.details = details
        super().__init__(f"[{condition}] Section {section_id}: {details}")


def _count_words(text: str) -> int:
    return len(text.split()) if text else 0


def _check_vague(text: str) -> List[str]:
    lower = text.lower()
    return [p for p in VAGUE_PHRASES if p in lower]


def _get_narration_text(section: dict) -> str:
    n = section.get("narration", "")
    if isinstance(n, dict):
        return n.get("full_text", "")
    return str(n) if n else ""


def _get_segments(section: dict) -> List[dict]:
    n = section.get("narration", {})
    if isinstance(n, dict):
        return n.get("segments", [])
    return []


# ══════════════════════════════════════
# INDIVIDUAL CHECKS
# ══════════════════════════════════════


def _check_text_layer_always_hidden(section: dict) -> List[V3ValidatorError]:
    """V3 Rule: text_layer must ALWAYS be 'hide'. No text overlays."""
    errors = []
    sid = section.get("section_id", 0)
    for i, seg in enumerate(_get_segments(section)):
        dd = seg.get("display_directives", {})
        text_layer = dd.get("text_layer", "")
        if text_layer == "show":
            errors.append(
                V3ValidatorError(
                    "v3_text_layer_show_forbidden",
                    sid,
                    f"Segment {i}: text_layer='show' is FORBIDDEN in V3. All content is delivered via avatar + Manim. Set text_layer='hide'.",
                )
            )
    return errors


def _check_renderer_valid(section: dict) -> List[V3ValidatorError]:
    """Renderer must be a known V3 value."""
    errors = []
    sid = section.get("section_id", 0)
    renderer = section.get("renderer", "")
    if renderer and renderer not in VALID_RENDERERS:
        errors.append(
            V3ValidatorError(
                "v3_invalid_renderer",
                sid,
                f"renderer='{renderer}' is not valid. Must be one of: {VALID_RENDERERS}",
            )
        )
    if renderer == "threejs":
        errors.append(
            V3ValidatorError(
                "v3_threejs_renderer_forbidden",
                sid,
                "renderer='threejs' is deprecated in V3. Use renderer='manim' for Math/Physics sections.",
            )
        )
    return errors


def _check_manim_spec(section: dict) -> List[V3ValidatorError]:
    """manim sections MUST have render_spec with manim_scene_spec (30+ words)."""
    errors = []
    sid = section.get("section_id", 0)
    renderer = section.get("renderer", "")

    if renderer != "manim":
        return errors

    render_spec = section.get("render_spec", {})
    if not render_spec:
        errors.append(
            V3ValidatorError(
                "v3_manim_missing_render_spec",
                sid,
                "renderer='manim' but section has no render_spec.",
            )
        )
        return errors

    segment_specs = render_spec.get("segment_specs", [])
    if not segment_specs:
        # Also check section-level manim_scene_spec as fallback
        section_spec = section.get("manim_scene_spec", "") or render_spec.get(
            "manim_scene_spec", ""
        )
        if not section_spec:
            errors.append(
                V3ValidatorError(
                    "v3_manim_missing_segment_specs",
                    sid,
                    "render_spec.segment_specs is empty and no section-level manim_scene_spec — no Manim animation spec provided.",
                )
            )
        return errors

    for i, spec in enumerate(segment_specs):
        manim_spec = spec.get("manim_scene_spec", "")
        if not manim_spec:
            errors.append(
                V3ValidatorError(
                    "v3_manim_spec_missing",
                    sid,
                    f"segment_spec[{i}].manim_scene_spec is missing — required for Manim generation.",
                )
            )
        elif _count_words(manim_spec) < MANIM_SPEC_MIN_WORDS:
            wc = _count_words(manim_spec)
            errors.append(
                V3ValidatorError(
                    "v3_manim_spec_too_short",
                    sid,
                    f"segment_spec[{i}].manim_scene_spec is {wc} words — minimum is {MANIM_SPEC_MIN_WORDS} words.",
                )
            )

        spec_duration = spec.get("segment_duration_seconds")
        if not spec_duration:
            errors.append(
                V3ValidatorError(
                    "v3_segment_duration_missing",
                    sid,
                    f"segment_spec[{i}].segment_duration_seconds not set — Manim generator needs this.",
                )
            )

        # Check vague language in manim_scene_spec
        if manim_spec:
            vague = _check_vague(manim_spec)
            if vague:
                errors.append(
                    V3ValidatorError(
                        "v3_vague_manim_spec",
                        sid,
                        f"segment_spec[{i}].manim_scene_spec contains vague language: {vague}",
                    )
                )

    return errors


def _check_segment_duration(section: dict) -> List[V3ValidatorError]:
    """segment_duration_seconds required at section level for content/example."""
    errors = []
    sid = section.get("section_id", 0)
    section_type = section.get("section_type", "")
    if section_type not in ("content", "example"):
        return errors
    if not section.get("segment_duration_seconds"):
        errors.append(
            V3ValidatorError(
                "v3_segment_duration_missing",
                sid,
                "content/example sections MUST have segment_duration_seconds set by the Director.",
            )
        )
    return errors


def _check_understanding_quiz(section: dict) -> List[V3ValidatorError]:
    """content/example sections MUST have understanding_quiz (mandatory, no skip condition)."""
    errors = []
    sid = section.get("section_id", 0)
    section_type = section.get("section_type", "")
    if section_type not in ("content", "example"):
        return errors

    quiz = section.get("understanding_quiz", {})
    if not quiz:
        errors.append(
            V3ValidatorError(
                "v3_understanding_quiz_missing",
                sid,
                "content/example sections MUST include understanding_quiz (no skip condition). "
                "Required fields: question, options (A/B/C/D), correct, explanation, narration.",
            )
        )
        return errors

    if not quiz.get("question"):
        errors.append(
            V3ValidatorError(
                "v3_understanding_quiz_missing_question",
                sid,
                "understanding_quiz.question is empty.",
            )
        )
    opts = quiz.get("options", {})
    if not opts:
        errors.append(
            V3ValidatorError(
                "v3_understanding_quiz_missing_options",
                sid,
                "understanding_quiz.options is empty.",
            )
        )
    elif len(opts) < 4:
        errors.append(
            V3ValidatorError(
                "v3_understanding_quiz_too_few_options",
                sid,
                f"understanding_quiz must have 4 options (A/B/C/D) — found {len(opts)}: {list(opts.keys())}",
            )
        )
    if not quiz.get("correct"):
        errors.append(
            V3ValidatorError(
                "v3_understanding_quiz_missing_answer",
                sid,
                "understanding_quiz.correct (answer key) is missing.",
            )
        )
    if not quiz.get("explanation"):
        errors.append(
            V3ValidatorError(
                "v3_understanding_quiz_missing_explanation",
                sid,
                "understanding_quiz.explanation is missing.",
            )
        )

    # C7: narration scripts required for 3-clip avatar generation
    narr = quiz.get("narration", {})
    if not narr:
        errors.append(
            V3ValidatorError(
                "v3_understanding_quiz_missing_narration",
                sid,
                "understanding_quiz.narration is missing. Required: question_script, correct_script, wrong_script.",
            )
        )
    else:
        for script_key in ("question_script", "correct_script", "wrong_script"):
            if not narr.get(script_key):
                errors.append(
                    V3ValidatorError(
                        "v3_understanding_quiz_missing_narration_script",
                        sid,
                        f"understanding_quiz.narration.{script_key} is missing or empty.",
                    )
                )

    return errors


def _check_quiz_section(section: dict) -> List[V3ValidatorError]:
    """Quiz sections must have 3 narration scripts per question for 3 avatar clips."""
    errors = []
    sid = section.get("section_id", 0)
    section_type = section.get("section_type", "")
    if section_type != "quiz":
        return errors

    questions = section.get("questions", [])
    if not questions:
        errors.append(
            V3ValidatorError(
                "v3_quiz_no_questions", sid, "Quiz section has no questions array."
            )
        )
        return errors

    for i, q in enumerate(questions):
        narr = q.get("narration", {})
        for script_key in ("question_script", "correct_script", "wrong_script"):
            if not narr.get(script_key):
                errors.append(
                    V3ValidatorError(
                        "v3_quiz_missing_narration_script",
                        sid,
                        f"Question {i} (id={q.get('question_id')}) missing narration.{script_key} — needed for 3 avatar clips.",
                    )
                )

        opts = q.get("options", {})
        if len(opts) < 4:
            errors.append(
                V3ValidatorError(
                    "v3_quiz_insufficient_options",
                    sid,
                    f"Question {i} has {len(opts)} options, minimum is 3 (A/B/C).",
                )
            )

        if not q.get("correct_option"):
            errors.append(
                V3ValidatorError(
                    "v3_quiz_missing_correct_option",
                    sid,
                    f"Question {i} has no correct_option set.",
                )
            )

    return errors


def _check_narration_length(section: dict) -> List[V3ValidatorError]:
    """content/example must meet minimum narration word counts."""
    errors = []
    sid = section.get("section_id", 0)
    section_type = section.get("section_type", "")
    if section_type not in ("content", "example"):
        return errors
    text = _get_narration_text(section)
    wc = _count_words(text)
    minimum = CONTENT_MIN_WORDS if section_type == "content" else EXAMPLE_MIN_WORDS
    if wc < minimum:
        errors.append(
            V3ValidatorError(
                "v3_narration_below_minimum",
                sid,
                f"{section_type} section has {wc} words, minimum is {minimum}.",
            )
        )
    return errors


def _check_display_directives(section: dict) -> List[V3ValidatorError]:
    """display_directives check — non-blocking warning only.
    V3 director early runs may omit these; player handles defaults."""
    return []  # Non-fatal: skipped during director stabilisation phase


# ══════════════════════════════════════
# SECTION VALIDATOR
# ══════════════════════════════════════


def validate_section_v3(section: dict) -> List[V3ValidatorError]:
    """Run all V3 checks on a single section."""
    errors = []
    errors.extend(_check_text_layer_always_hidden(section))
    errors.extend(_check_renderer_valid(section))
    errors.extend(_check_manim_spec(section))
    errors.extend(_check_segment_duration(section))
    errors.extend(_check_understanding_quiz(section))
    errors.extend(_check_quiz_section(section))
    errors.extend(_check_narration_length(section))
    errors.extend(_check_display_directives(section))
    return errors


# ══════════════════════════════════════
# PRESENTATION VALIDATOR
# ══════════════════════════════════════


def validate_presentation_v3(presentation: dict) -> Tuple[bool, List[V3ValidatorError]]:
    """
    Validate entire V3 presentation.json.

    Returns:
        (is_valid: bool, errors: List[V3ValidatorError])
    """
    all_errors: List[V3ValidatorError] = []
    sections = presentation.get("sections", [])

    # Structure checks
    section_types = {s.get("section_type") for s in sections}
    for required in REQUIRED_SECTION_TYPES:
        if required not in section_types:
            all_errors.append(
                V3ValidatorError(
                    f"v3_missing_{required}_section",
                    0,
                    f"Presentation is missing required '{required}' section.",
                )
            )

    # Per-section checks
    for section in sections:
        all_errors.extend(validate_section_v3(section))

    return len(all_errors) == 0, all_errors


def format_v3_report(errors: List[V3ValidatorError]) -> str:
    """Format V3 validation errors into a readable report."""
    if not errors:
        return "✅ V3 Validation passed — no issues found."

    lines = [
        "=" * 60,
        "V3 VALIDATOR REPORT",
        "=" * 60,
        f"Total failures: {len(errors)}",
        "",
    ]
    by_condition: Dict[str, List[V3ValidatorError]] = {}
    for e in errors:
        by_condition.setdefault(e.condition, []).append(e)

    for cond, errs in by_condition.items():
        lines.append(f"\n[{cond}] — {len(errs)} occurrence(s)")
        for e in errs:
            lines.append(f"  Section {e.section_id}: {e.details}")

    lines.append("\n" + "=" * 60)
    return "\n".join(lines)


# ══════════════════════════════════════
# CLI USAGE
# ══════════════════════════════════════

if __name__ == "__main__":
    import json, sys

    path = sys.argv[1] if len(sys.argv) > 1 else "presentation.json"
    with open(path) as f:
        data = json.load(f)
    ok, errors = validate_presentation_v3(data)
    print(format_v3_report(errors))
    sys.exit(0 if ok else 1)
